services:
    web:
        environment:
            - EXTENSION_KEY=singleview
            - PACKAGE_NAME=sourcebroker/singleview

            - TYPO3_INSTALL_DB_DRIVER=mysqli
            - TYPO3_INSTALL_DB_USER=root
            - TYPO3_INSTALL_DB_PASSWORD=root
            - TYPO3_INSTALL_DB_HOST=db
            - TYPO3_INSTALL_DB_UNIX_SOCKET=
            - TYPO3_INSTALL_DB_USE_EXISTING=0
            - TYPO3_INSTALL_ADMIN_USER=admin
            - TYPO3_INSTALL_ADMIN_PASSWORD=Joh316!!
            - TYPO3_INSTALL_SITE_NAME=EXT:singleview Dev Environment
            - TYPO3_INSTALL_SITE_SETUP_TYPE=site
            - TYPO3_INSTALL_WEB_SERVER_CONFIG=apache

            # TYPO3 v13 config
            - TYPO3_DB_DRIVER=mysqli
            - TYPO3_DB_USERNAME=root
            - TYPO3_DB_PASSWORD=root
            - TYPO3_DB_HOST=db
            - TYPO3_SETUP_ADMIN_EMAIL=admin@example.com
            - TYPO3_SETUP_ADMIN_USERNAME=admin
            - TYPO3_SETUP_ADMIN_PASSWORD=Joh316!!
            - TYPO3_PROJECT_NAME=EXT:singleview Dev Environment
            - TYPO3_SERVER_TYPE=apache
        volumes:
            - type: bind
              source: ../
              target: /var/www/singleview
              consistency: cached
            - v13-data:/var/www/html/v13
            - v14-data:/var/www/html/v14
volumes:
    v13-data:
        name: "${DDEV_SITENAME}-v13-data"
    v14-data:
        name: "${DDEV_SITENAME}-v14-data"
